DROP SEQUENCE SEC_PACIENTE_OID;
DROP SEQUENCE SEC_USUARIO_OID;
DROP SEQUENCE SEC_CITA_OID;
DROP SEQUENCE SEC_TRATAMIENTO_OID;
DROP SEQUENCE SEC_ESPECIALIDAD_OID;
DROP SEQUENCE SEC_DOCTORA_OID;

DROP TABLE USUARIO;
DROP TABLE CITA;
DROP TABLE TRATAMIENTO;
DROP TABLE DOCTORA;
DROP TABLE ESPECIALIDAD;
DROP TABLE PACIENTE;

CREATE TABLE PACIENTE (
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(75) NOT NULL,
    DNI VARCHAR2(10) NOT NULL UNIQUE,
    FECHA_NACIMIENTO DATE NOT NULL,
	CORREO VARCHAR2(75) NOT NULL UNIQUE,
	POBLACION VARCHAR2(75) NOT NULL,
	DIRECCION VARCHAR2(75) NOT NULL,
    FECHAALTA DATE NOT NULL,
	SEGURO VARCHAR2(10) NOT NULL,
	NOMBRE_TUTOR VARCHAR2(75),
	TELEFONO_TUTOR VARCHAR2(75),
	OID_PACIENTE INTEGER NOT NULL,
	PRIMARY KEY (OID_PACIENTE) );

CREATE TABLE ESPECIALIDAD (
	NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
	OID_ESPECIALIDAD INTEGER NOT NULL,
	PRIMARY KEY (OID_ESPECIALIDAD));   
    
CREATE TABLE DOCTORA (
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(75),
    DNI VARCHAR2(10) NOT NULL UNIQUE,
    FECHA_NACIMIENTO DATE NOT NULL,
	POBLACION VARCHAR2(75) NOT NULL,
	DIRECCION VARCHAR2(75) NOT NULL,
    FECHAALTA DATE NOT NULL,
	SUELDO VARCHAR2(75) NOT NULL,
	TELEFONO VARCHAR2(75) UNIQUE,
    CODIGODOCTORA VARCHAR(75) NOT NULL,
    OID_ESPECIALIDAD INTEGER NOT NULL,
    OID_DOCTORA INTEGER NOT NULL,
	FOREIGN KEY (OID_ESPECIALIDAD) REFERENCES ESPECIALIDAD,
    PRIMARY KEY (OID_DOCTORA) );
    

CREATE TABLE TRATAMIENTO (
	NOMBRE VARCHAR2(25) NOT NULL,
	COSTE VARCHAR2(25) NOT NULL,
	OID_TRATAMIENTO INTEGER NOT NULL,
    OID_ESPECIALIDAD INTEGER NOT NULL,
	FOREIGN KEY (OID_ESPECIALIDAD) REFERENCES ESPECIALIDAD,
	PRIMARY KEY (OID_TRATAMIENTO));
    
CREATE TABLE CITA (
	FECHACITA DATE NOT NULL,
	HORACITA VARCHAR2(25) NOT NULL,
	CONSULTA VARCHAR2(25) NOT NULL,
	OID_CITA INTEGER NOT NULL,
	OID_PACIENTE INTEGER NOT NULL,
	OID_DOCTORA INTEGER NOT NULL,
	OID_TRATAMIENTO INTEGER NOT NULL,
    FOREIGN KEY (OID_PACIENTE) REFERENCES PACIENTE,
    FOREIGN KEY (OID_DOCTORA) REFERENCES DOCTORA,
    FOREIGN KEY (OID_TRATAMIENTO) REFERENCES TRATAMIENTO,
	PRIMARY KEY (OID_CITA));
    
CREATE TABLE USUARIO (
	CORREO VARCHAR2(75) NOT NULL UNIQUE,
	PASS VARCHAR2(25) NOT NULL,
	OID_USUARIO INTEGER NOT NULL,
	PRIMARY KEY (OID_USUARIO));
	

CREATE SEQUENCE SEC_ESPECIALIDAD_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;


CREATE OR REPLACE TRIGGER INSERTAR_ESPECIALIDAD_OID
BEFORE INSERT ON ESPECIALIDAD
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_ESPECIALIDAD_OID.NEXTVAL INTO :NEW.OID_ESPECIALIDAD FROM DUAL;
END;
/

CREATE SEQUENCE SEC_DOCTORA_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER INSERTAR_DOCTORA_OID
BEFORE INSERT ON DOCTORA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_DOCTORA_OID.NEXTVAL INTO :NEW.OID_DOCTORA FROM DUAL;
END;
/

CREATE SEQUENCE SEC_PACIENTE_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;


CREATE OR REPLACE TRIGGER INSERTAR_PACIENTE_OID
BEFORE INSERT ON PACIENTE
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_PACIENTE_OID.NEXTVAL INTO :NEW.OID_PACIENTE FROM DUAL;
END;
/

CREATE SEQUENCE SEC_TRATAMIENTO_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;


CREATE OR REPLACE TRIGGER INSERTAR_TRATAMIENTO_OID
BEFORE INSERT ON TRATAMIENTO
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_TRATAMIENTO_OID.NEXTVAL INTO :NEW.OID_TRATAMIENTO FROM DUAL;
END;
/

CREATE SEQUENCE SEC_CITA_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;


CREATE OR REPLACE TRIGGER INSERTAR_CITA_OID
BEFORE INSERT ON CITA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_CITA_OID.NEXTVAL INTO :NEW.OID_CITA FROM DUAL;
END;
/

CREATE SEQUENCE SEC_USUARIO_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;


CREATE OR REPLACE TRIGGER INSERTAR_USUARIO_OID
BEFORE INSERT ON USUARIO
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_USUARIO_OID.NEXTVAL INTO :NEW.OID_USUARIO FROM DUAL;
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_PACIENTE 
  (P_NOM IN PACIENTE.NOMBRE%TYPE,
   P_APE IN PACIENTE.APELLIDOS%TYPE,
   P_DNI IN PACIENTE.DNI%TYPE,
   P_FECHA_NAC IN PACIENTE.FECHA_NACIMIENTO%TYPE,
   P_CORREO IN PACIENTE.CORREO%TYPE,
   P_POBLACION IN PACIENTE.POBLACION%TYPE,
   P_DIRECCION IN PACIENTE.DIRECCION%TYPE,
   P_FECHAALTA IN PACIENTE.FECHAALTA%TYPE,
   P_SEGURO IN PACIENTE.SEGURO%TYPE,
   P_NTUTOR IN PACIENTE.NOMBRE_TUTOR%TYPE,
   P_TTUTOR IN PACIENTE.TELEFONO_TUTOR%TYPE
   ) IS
BEGIN
  INSERT INTO PACIENTE(NOMBRE, APELLIDOS, DNI, FECHA_NACIMIENTO,CORREO,POBLACION,DIRECCION,FECHAALTA,SEGURO,NOMBRE_TUTOR,TELEFONO_TUTOR)
  VALUES (P_NOM ,P_APE,P_DNI,P_FECHA_NAC,P_CORREO,P_POBLACION,P_DIRECCION,P_FECHAALTA,P_SEGURO,P_NTUTOR,P_TTUTOR);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_ESPECIALIDAD 
  (E_NOM IN ESPECIALIDAD.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO ESPECIALIDAD(NOMBRE)
  VALUES (E_NOM);
END;
/


CREATE OR REPLACE PROCEDURE INSERTAR_TRATAMIENTO 
  (P_NOM IN TRATAMIENTO.NOMBRE%TYPE,
   P_COS IN TRATAMIENTO.COSTE%TYPE,
   P_OID_ESPECIALIDAD IN TRATAMIENTO.OID_ESPECIALIDAD%TYPE
   ) IS
BEGIN
  INSERT INTO TRATAMIENTO(NOMBRE, COSTE, OID_ESPECIALIDAD)
  VALUES (P_NOM ,P_COS, P_OID_ESPECIALIDAD);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_CITA 
  (P_FECHACITA IN CITA.FECHACITA%TYPE,
   P_HORACITA IN CITA.HORACITA%TYPE,
   P_CONSULTA IN CITA.CONSULTA%TYPE,
   P_OID_PACIENTE IN CITA.OID_PACIENTE%TYPE,
   P_OID_DOCTORA IN CITA.OID_DOCTORA%TYPE,
   P_OID_TRATAMIENTO IN CITA.OID_TRATAMIENTO%TYPE
   ) IS
BEGIN
  INSERT INTO CITA(FECHACITA, HORACITA, CONSULTA, OID_PACIENTE, OID_DOCTORA, OID_TRATAMIENTO)
  VALUES (P_FECHACITA,P_HORACITA,P_CONSULTA, P_OID_PACIENTE, P_OID_DOCTORA, P_OID_TRATAMIENTO);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO 
  (P_CORREO IN USUARIO.CORREO%TYPE,
   P_PASS IN USUARIO.PASS%TYPE
   ) IS
BEGIN
  INSERT INTO USUARIO(CORREO, PASS)
  VALUES (P_CORREO,P_PASS);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_DOCTORA 
  (P_NOM IN DOCTORA.NOMBRE%TYPE,
   P_APE IN DOCTORA.APELLIDOS%TYPE,
   P_DNI IN DOCTORA.DNI%TYPE,
   P_FECHA_NAC IN DOCTORA.FECHA_NACIMIENTO%TYPE,
   P_POBLACION IN DOCTORA.POBLACION%TYPE,
   P_DIRECCION IN DOCTORA.DIRECCION%TYPE,
   P_FECHAALTA IN DOCTORA.FECHAALTA%TYPE,
   P_TEL IN DOCTORA.TELEFONO%TYPE,
   P_SUELDO IN DOCTORA.SUELDO%TYPE,
   P_CODIGODOCTORA IN DOCTORA.CODIGODOCTORA%TYPE,
   P_OID_ESPECIALIDAD IN DOCTORA.OID_ESPECIALIDAD%TYPE
   ) IS
BEGIN
  INSERT INTO DOCTORA(NOMBRE, APELLIDOS, DNI, FECHA_NACIMIENTO,POBLACION,DIRECCION,FECHAALTA,TELEFONO,SUELDO,CODIGODOCTORA,OID_ESPECIALIDAD)
  VALUES (P_NOM ,P_APE,P_DNI,P_FECHA_NAC,P_POBLACION,P_DIRECCION,P_FECHAALTA,P_TEL,P_SUELDO,P_CODIGODOCTORA,P_OID_ESPECIALIDAD);
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_PACIENTE(
   P_OID_PACIENTE_A_MOD IN PACIENTE.OID_PACIENTE%TYPE,
   P_NOM IN PACIENTE.NOMBRE%TYPE,
   P_APE IN PACIENTE.APELLIDOS%TYPE,
   P_DNI IN PACIENTE.DNI%TYPE,
   P_FECHA_NAC IN PACIENTE.FECHA_NACIMIENTO%TYPE,
   P_CORREO IN PACIENTE.CORREO%TYPE,
   P_POBLACION IN PACIENTE.POBLACION%TYPE,
   P_DIRECCION IN PACIENTE.DIRECCION%TYPE,
   P_FECHAALTA IN PACIENTE.FECHAALTA%TYPE,
   P_SEGURO IN PACIENTE.SEGURO%TYPE,
   P_NTUTOR IN PACIENTE.NOMBRE_TUTOR%TYPE,
   P_TTUTOR IN PACIENTE.TELEFONO_TUTOR%TYPE
   )IS
BEGIN
    UPDATE Paciente
    SET NOMBRE=P_NOM, APELLIDOS=P_APE, DNI=P_DNI, FECHA_NACIMIENTO=P_FECHA_NAC,CORREO=P_CORREO,POBLACION=P_POBLACION,DIRECCION=P_DIRECCION,FECHAALTA=P_FECHAALTA,SEGURO=P_SEGURO,NOMBRE_TUTOR=P_NTUTOR,TELEFONO_TUTOR=P_TTUTOR
    WHERE OID_PACIENTE = P_OID_PACIENTE_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_USUARIO 
(OID_USUARIO_A_MOD IN USUARIO.OID_USUARIO%TYPE,
 P_CORREO IN USUARIO.CORREO%TYPE,
 P_PASS IN USUARIO.PASS%TYPE) IS
BEGIN
  UPDATE USUARIO SET CORREO=P_CORREO,PASS=P_PASS
  WHERE OID_USUARIO = OID_USUARIO_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_ESPECIALIDAD(
   E_OID_ESPECIALIDAD_A_MOD IN ESPECIALIDAD.OID_ESPECIALIDAD%TYPE,
   E_NOM IN ESPECIALIDAD.NOMBRE%TYPE)IS
BEGIN
    UPDATE Especialidad
    SET NOMBRE=E_NOM
    WHERE OID_ESPECIALIDAD = E_OID_ESPECIALIDAD_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_TRATAMIENTO(OID_TRATAMIENTO_A_MOD IN TRATAMIENTO.OID_TRATAMIENTO%TYPE,
   P_NOM IN TRATAMIENTO.NOMBRE%TYPE,
   P_COS IN TRATAMIENTO.COSTE%TYPE,
   P_OID_ESPECIALIDAD IN TRATAMIENTO.OID_ESPECIALIDAD%TYPE
   )IS
BEGIN
    UPDATE TRATAMIENTO SET NOMBRE=P_NOM, COSTE=P_COS, OID_ESPECIALIDAD=P_OID_ESPECIALIDAD
    WHERE OID_TRATAMIENTO = OID_TRATAMIENTO_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_CITA(C_OID_CITA IN CITA.OID_CITA%TYPE, C_FECHA_CITA IN CITA.FECHACITA%TYPE,
   C_HORA_CITA IN CITA.HORACITA%TYPE,
   C_CONSULTA IN CITA.CONSULTA%TYPE,
   P_OID_PACIENTE IN CITA.OID_PACIENTE%TYPE,
   P_OID_DOCTORA IN CITA.OID_DOCTORA%TYPE,
   P_OID_TRATAMIENTO IN CITA.OID_TRATAMIENTO%TYPE
   )IS
BEGIN
    UPDATE Cita
    SET FECHACITA=C_FECHA_CITA, HORACITA=C_HORA_CITA, CONSULTA=C_CONSULTA, OID_PACIENTE = P_OID_PACIENTE, OID_DOCTORA=P_OID_DOCTORA, OID_TRATAMIENTO=P_OID_TRATAMIENTO
    WHERE OID_CITA = C_OID_CITA;
END;
/

CREATE OR REPLACE PROCEDURE ACTUALIZAR_DOCTORA(
   P_OID_DOCTORA IN DOCTORA.OID_DOCTORA%TYPE,
   P_NOM IN DOCTORA.NOMBRE%TYPE,
   P_APE IN DOCTORA.APELLIDOS%TYPE,
   P_DNI IN DOCTORA.DNI%TYPE,
   P_FECHA_NAC IN DOCTORA.FECHA_NACIMIENTO%TYPE,
   P_POBLACION IN DOCTORA.POBLACION%TYPE,
   P_DIRECCION IN DOCTORA.DIRECCION%TYPE,
   P_FECHAALTA IN DOCTORA.FECHAALTA%TYPE,
   P_TEL IN DOCTORA.TELEFONO%TYPE,
   P_SUELDO IN DOCTORA.SUELDO%TYPE,
   P_OID_ESPECIALIDAD IN DOCTORA.OID_ESPECIALIDAD%TYPE
   )IS
BEGIN
    UPDATE Doctora
    SET NOMBRE=P_NOM, APELLIDOS=P_APE, DNI=P_DNI, FECHA_NACIMIENTO=P_FECHA_NAC,POBLACION=P_POBLACION,DIRECCION=P_DIRECCION,FECHAALTA=P_FECHAALTA,TELEFONO=P_TEL,SUELDO=P_SUELDO, OID_ESPECIALIDAD=P_OID_ESPECIALIDAD
    WHERE OID_DOCTORA=P_OID_DOCTORA;
END;
/


CREATE OR REPLACE PROCEDURE ELIMINAR_ESPECIALIDAD(OID_ESPECIALIDAD_A_QUITAR IN ESPECIALIDAD.OID_ESPECIALIDAD%TYPE) AS
BEGIN
  DELETE FROM DOCTORA WHERE  OID_ESPECIALIDAD = OID_ESPECIALIDAD_A_QUITAR;
  DELETE FROM TRATAMIENTO WHERE  OID_ESPECIALIDAD = OID_ESPECIALIDAD_A_QUITAR;
  DELETE FROM ESPECIALIDAD WHERE OID_ESPECIALIDAD = OID_ESPECIALIDAD_A_QUITAR;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_USUARIO(OID_USUARIO_A_QUITAR IN USUARIO.OID_USUARIO%TYPE) AS
BEGIN
  DELETE FROM USUARIO WHERE OID_USUARIO = OID_USUARIO_A_QUITAR;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_CITA(OID_CITA_A_QUITAR IN CITA.OID_CITA%TYPE) AS
BEGIN
  DELETE FROM CITA WHERE OID_CITA = OID_CITA_A_QUITAR;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_TRATAMIENTO(OID_TRATAMIENTO_A_QUITAR IN TRATAMIENTO.OID_TRATAMIENTO%TYPE) AS
BEGIN
  DELETE FROM CITA WHERE OID_TRATAMIENTO = OID_TRATAMIENTO_A_QUITAR;
  DELETE FROM TRATAMIENTO WHERE OID_TRATAMIENTO = OID_TRATAMIENTO_A_QUITAR;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_PACIENTE(OID_PACIENTE_A_QUITAR IN PACIENTE.OID_PACIENTE%TYPE) AS
BEGIN
  DELETE FROM CITA WHERE OID_PACIENTE = OID_PACIENTE_A_QUITAR;
  DELETE FROM PACIENTE WHERE OID_PACIENTE = OID_PACIENTE_A_QUITAR;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_DOCTORA(CODIGO_DOCTORA_A_QUITAR IN doctora.oid_doctora%TYPE) AS
BEGIN
    DELETE FROM CITA WHERE oid_doctora = CODIGO_DOCTORA_A_QUITAR;
  DELETE FROM DOCTORA WHERE oid_doctora = CODIGO_DOCTORA_A_QUITAR;
END;
/
